destination:  ./_site

layouts_dir:  _layouts
includes_dir: _includes

baseurl: /docs

defaults:
  -
    values:
      layout: "docs"

include:     ['.htaccess']
exclude:
  - _config.yaml
  - example.info
  - Gemfile
  - Gemfile.lock
  - README.md

keep_files:  ['.git']

markdown:    kramdown

permalink:   :title/

collections:
  - patterns
  - docs_quick-start
  - docs_using-snyk
  - docs_faqs
  - docs_ci
  - docs_github
  - docs_orgs
  - docs_security
  - docs_badges
  - docs_landing
